services:
  jupyter:
    build: 
      context: .
      dockerfile: ./docker/jupyter/Dockerfile
    volumes:
      - ./work:/home/jovyan/work
      # - $PWD/work:/workspace
    ports:
      - 8888:8888
    deploy:
      resources:
        limits:
          memory: 64G
        reservations:
          memory: 2G
    command: "start-notebook.sh --NotebookApp.token="
    # command: "jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root"

# docker run -it --rm \
#     -p 8888:8888 \
#     -v $PWD/workspace:/workspace \
#     -w /workspace \
#     intel/intel-extension-for-pytorch:2.4.0-pip-jupyter

# docker compose up --build